baseURL = "https://lieflike.github.io/"
languageCode = "en-us"
title = "Life Files"
description = "All things that happened in my life that may be useful to you. For educational or entertainment purposes."
theme = "ananke"



[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"


[params]
  author = ""
  favicon = ""
  site_logo = ""
  description = ""
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/kunal-shinde--f0YLss50Bs-unsplash.jpg"
  recent_posts_number = 2
